version: "3.7"
services:

  app:
    build:
      args:
        user: diego
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php:8.0-fpm
    container_name: project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - project

  db:
    image: mysql:5.7
    container_name: project-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_TCP_PORT: 3306
    ports:
     - 3306:3306
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql
    networks:
      - project

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - project

  nginx:
    image: nginx:1.17-alpine
    container_name: project-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - project

networks:
  project:
    driver: bridge